### PR TITLE
Added Reducio spell

### PR DESCRIPTION
**Pull request by PalAditya**
Hi, I am a great Harry Potter fan and this project seemed perfectly aligned to my tastes. I added the **Reducio** spell, which mimics **tar** due to the fact that they both *shrink* objects. Please check and merge if found useful 😄

### CODE REVIEW

**Comment by gabru-md** [comment]
Hi @PalAditya . Great to hear that you liked this project.
Thanks for your contribution. We really admire people who put in efforts to improve the project.
I am really glad that you liked this and contributed to it.

**Comment by gabru-md** [comment]
Also, can you please provide a working GIF maybe? so that we can get it merged asap.

Thanks. Cheers !

**Comment by PalAditya** [comment]
Working *GIF* as in like the one for **Geminio** and **Lumos** (at the bottom), or like the *png* ones for like say, **Avada Kedavra**? 🤔

**Comment by gabru-md** [comment]
no no, just your spell. so that we can verify it works. a gif or small video. that's it

**Comment by PalAditya** [comment]
Here you go: [Gif](https://asciinema.org/a/iiJBtua7khiN8pKCflqqizxnH) (asciinema gif) 😄 
You can see the image in README too.
Do let me know if something else needs to be done.

**Comment by PalAditya** [comment]
[Gif 2](https://asciinema.org/a/paLxBR2BwONDnXXQdOIRWUxBy) because I forgot to record the `help` feature in the previous one :smile:

**Comment by PalAditya** [comment]
Hi, can I get some feedback on this please? My inner Potterhead is killing me 😅

**Comment by gabru-md** [comment]
looks good. requires a few changes. I'll add them

**Pull request merged**
