### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by arpitjainds**
Added Emphasis to the Cheers!

### CODE REVIEW

**Comment by Ananthavijay** [comment]
I think this PR refers to this issue https://github.com/yogdaan/LinuxSpells/issues/17

**Comment by arpitjainds** [comment]
Yea. It belongs to #17 . Still you can merge it right?

**Comment by Ananthavijay** [comment]
I don't have push access. Don't worry @gabru-md will do it

**Review by gabru-md — APPROVED** [review]
thank you for your PR

**Pull request merged**
